#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
name: Update Checker
env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: main
on:
  workflow_dispatch:
  #schedule:
  #  - cron: 0 */18 * * *
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Cache commit hash
      id: cacheHash
      uses: actions/cache@v4
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save new Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo "${{ steps.getHash.outputs.commitHash }}" > .commitHash

    - name: Trigger build workflow
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: repository_dispatch

    - name: Delete old workflow runs
      uses: actions/github-script@v7
      with:
        script: |
          const days = 1;
          const keepRuns = 1;
          const cutoff = new Date();
          cutoff.setDate(cutoff.getDate() - days);
          const {data:runs}=await github.rest.actions.listWorkflowRuns({
            owner:context.repo.owner,
            repo:context.repo.repo,
            workflow_id:context.workflow,
            per_page:100
          });
          let delRuns=runs.workflow_runs.filter(run=>new Date(run.created_at)<cutoff);
          if(delRuns.length>keepRuns) delRuns=delRuns.slice(keepRuns);
          for(const r of delRuns){
            await github.rest.actions.deleteWorkflowRun({owner:context.repo.owner,repo:context.repo.repo,run_id:r.id});
          }
